openapi: 3.0.0
info:
  title: Mail API
  version: '1.0'
paths:
  /healthcode/pc/email/preSutBooking/save:
    post:
      tags:
        - Mail
      summary: Update stored data
      description: Update the subjectDailyReport and sendTime in the stored data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subjectDailyReport:
                  type: string
                sendTime:
                  type: string
                  format: date-time
      responses:
        200:
          description: Successfully updated the data
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  success:
                    type: boolean
                  data:
                    type: object
                  msg:
                    type: string
